name: Check Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn --frozen-lockfile

      - name: Check formatting with Prettier
        run: npx prettier --check .
